(* ====================================================================== *)
(* EchoAssumptions.v -- THE ASSUMPTION AUDIT of the APPLICATION theorem.   *)
(*                                                                        *)
(* [Print Assumptions] on                                                 *)
(* [UInitBootAdequacy.echo_adequacy_modulo_phi]: safety of the whole       *)
(* machine plus the UART trace property, for the "echo hello world"        *)
(* application running on an unmodified xv6 -- /init forks a shell, the    *)
(* shell forks and execs /echo, and what comes out of the console is a     *)
(* legal session transcript.                                               *)
(*                                                                        *)
(* WHY A SECOND AUDIT FILE EXISTS, beside [SystemAssumptions.v].  The two  *)
(* theorems are different instantiations of the same adequacy chain and    *)
(* NEITHER CONE CONTAINS THE OTHER:                                        *)
(*                                                                        *)
(*   [SystemAdequacy.xv6_fs_adequacy_xv6Σ] is the system theorem at the    *)
(*   trivial application ([App.app_triv]) -- safety and the file system's  *)
(*   durability, with every image fact discharged by computation at the    *)
(*   2,048,000 bytes mkfs wrote.  It does not mention a user program.      *)
(*                                                                        *)
(*   [echo_adequacy_modulo_phi] is the same chain at [AppEcho.app_echo],   *)
(*   and its cone additionally covers [App], [AppEcho], [EchoOut],         *)
(*   [EchoLinks*], [EchoDisc] and the whole [Uk*]/[USh*]/[UInit*]/         *)
(*   [UEcho*] user-program tier -- thousands of proofs the system          *)
(*   theorem's audit never walks.                                          *)
(*                                                                        *)
(* So the system audit says nothing about whether the PROGRAM tier leaked  *)
(* an axiom, and until this file existed the only evidence for that was a  *)
(* grep for [Admitted] and [Axiom].  A grep cannot see through a sealed    *)
(* functor: a [Spec*.v] module [Parameter] that no [Link*.v] ever          *)
(* discharged would sit in the proof term unmentioned by any source line.  *)
(* [Print Assumptions] is the only check that does see it.  That is the    *)
(* gap this file closes, and it is why the echo theorem's audit is not a   *)
(* duplicate of the system theorem's.                                      *)
(*                                                                        *)
(* EXPECT EXACTLY FOURTEEN, and the split matters:                         *)
(*                                                                        *)
(*   1  [functional_extensionality_dep]                                    *)
(*   2  [xv6iris_extras.resv_matches] / [_is_valid] -- the LR/SC           *)
(*      reservation predicates, this project's own [Parameter]s            *)
(*  11  Rocq's [PrimString]/[PrimInt63] primitives                         *)
(*      ([PrimString.string]/[.get]/[.cat]/[.length], [PrimInt63.int]/     *)
(*      [.eqb]/[.sub]/[.lsl]/[.lsr]/[.land]/[.lor])                        *)
(*                                                                        *)
(* THAT IS THE SYSTEM THEOREM'S THIRTEEN PLUS [PrimString.length], AND     *)
(* NOTHING ELSE.  The extra one is not a new KIND of assumption: it is the *)
(* eleventh Rocq string primitive, reached through                         *)
(* [PStringBytes.pstring_hex_length] (iris/PStringBytes.v:56), the         *)
(* byte-count [pstring_hex_bytes] decodes a hex-imported binary blob by.   *)
(* Every literal binary in the tree -- the user ELF images and the mkfs    *)
(* disk image -- arrives that way; the echo theorem's cone forces the      *)
(* length where the system theorem's does not.                             *)
(*                                                                        *)
(* WHAT THE FOURTEEN DO NOT INCLUDE is the point of this file.  No         *)
(* [Admitted], no [Axiom] of this project's beyond the two named           *)
(* reservation [Parameter]s, and -- the thing only [Print Assumptions] can *)
(* certify -- NO [Spec*]/[Link*] MODULE PARAMETER.  Every deliberately     *)
(* unproven kernel function the program tier calls through is discharged   *)
(* inside this theorem's cone.  ANYTHING ELSE IS A REGRESSION.             *)
(*                                                                        *)
(* FIRST MEASURED 2026-09-14, immediately after lane R3 closed the last    *)
(* hypothesis ([Hsh_owed]); the theorem's own premises are then the        *)
(* power-on machine state and the disk image and nothing else.  Note that  *)
(* a theorem's PREMISES never appear in a [Print Assumptions] -- they are  *)
(* part of its statement -- so this list would have looked the same while  *)
(* [Hsh_owed] was still open.  The two checks are complementary and        *)
(* neither substitutes for the other.                                      *)
(*                                                                        *)
(* WHY IT IS OUT OF [iris/_CoqProject], same as [SystemAssumptions.v].     *)
(* [Print Assumptions] re-cooks every opaque proof term in the transitive  *)
(* cone out of its section and re-substitutes it through its functor; the  *)
(* system theorem's costs ~379 s on the strictly serial build tail, and    *)
(* this one walks a larger cone.  Paying it on every developer's every     *)
(* build is not worth it, so the audit is compiled by `make audit-echo`    *)
(* instead.  The commented row in [iris/_CoqProject] is what tells the     *)
(* coverage checker ([tools/proof_coverage.py]) that this file is out of   *)
(* the coq_makefile build ON PURPOSE rather than by accident.              *)
(*                                                                        *)
(* KEEP IT TO ONE [Print Assumptions], for [SystemAssumptions.v]'s         *)
(* reason: consecutive calls share NOTHING (measured back to back in one   *)
(* process, 94.5 s then 100.6 s), so a second command here would not ride  *)
(* along on the first, it would double the bill.                           *)
(*                                                                        *)
(* THE OTHER HALF OF THE TRUSTED BASE -- what a reader must READ for the   *)
(* statement to MEAN what they think -- is not here and is not an axiom    *)
(* question.  For this theorem it is above all [EchoDisc.v]: the trace     *)
(* predicate [disc]/[good_out] IS the specification, and a [Print          *)
(* Assumptions] of a theorem about the wrong predicate is worth nothing.   *)
(* See tools/tcb/ and claude-notes/design/adequacy.md.                     *)
(* ====================================================================== *)
Require Import UInitBootAdequacy.

Print Assumptions echo_adequacy_modulo_phi.
