(* ====================================================================== *)
(* FileAssumptions.v -- THE ASSUMPTION AUDIT of the FILE APPLICATION's     *)
(* top-level theorem.                                                     *)
(*                                                                        *)
(* [Print Assumptions] on [UInitFile.file_adequacy_closed]:               *)
(* safety of the whole machine plus the file-and-console trace property    *)
(* for the application of claude-notes/design/app-file.md -- the user      *)
(* types `echo w1 ... wn`, `echo w1 ... wn > f` and `cat f` at the console *)
(* of an unmodified xv6, and the file f never holds anything but what an   *)
(* `echo ... > f` line put there, this era or an earlier one.              *)
(*                                                                        *)
(* WHY A FOURTH AUDIT FILE, beside [SystemAssumptions.v],                  *)
(* [EchoAssumptions.v] and [TreeAssumptions.v]: for [EchoAssumptions.v]'s  *)
(* own reason, and no two of the four cones contain each other.  The       *)
(* system audit walks no application tier at all.  The echo audit walks    *)
(* [AppEcho]/[EchoOut]/[USh*] and never [FileDisc]/[FileOutPure]/          *)
(* [FileOut]/[FileLinks]/[AppFile]/[AppFileRec]/[FileDiscDec].  The tree   *)
(* audit walks [AppTree]/[TreeView]/[TreeMove]/[TreeImg] and none of       *)
(* either.  A grep for [Axiom] and [Admitted] cannot see a sealed [Spec*]  *)
(* module [Parameter]; this is the check that does, for this cone.         *)
(*                                                                        *)
(* THE THEOREM IS CLOSED (2026-09-22, the app-file worklist's item 4):      *)
(* [file_adequacy_closed] is [UFileBootAdequacy.file_adequacy_fileSig] with *)
(* its one remaining premise -- [Hprog : file_prog_law], the first          *)
(* process's exec bundle -- discharged by [UInitFile.file_Hinit_boot],      *)
(* which is [UInitFileBoot.file_Hinit_boot_at] at the record's two          *)
(* equations.  It has NO premise this tree owes: the three hardware facts   *)
(* of the image (generation, power, the mkfs disk) are its binders and are  *)
(* about the machine, not the proof.  So the list below is the whole of    *)
(* what the theorem rests on.                                              *)
(*                                                                        *)
(* EXPECT EXACTLY FOURTEEN -- the ECHO theorem's fourteen, and the same    *)
(* split:                                                                  *)
(*                                                                        *)
(*   1  [functional_extensionality_dep]                                    *)
(*   2  [xv6iris_extras.resv_matches] / [_is_valid] -- the LR/SC           *)
(*      reservation predicates, this project's own [Parameter]s            *)
(*  11  Rocq's [PrimString]/[PrimInt63] primitives                         *)
(*      ([PrimString.string]/[.get]/[.cat]/[.length], [PrimInt63.int]/     *)
(*      [.eqb]/[.sub]/[.lsl]/[.lsr]/[.land]/[.lor])                        *)
(*                                                                        *)
(* The primitives are there because the statement names a                  *)
(* [PrimString]-backed disk image; [Primitive _] has no body, which the    *)
(* traversal classifies like an axiom.  The eleventh is reached through    *)
(* [PStringBytes.pstring_hex_length], the byte-count every hex-imported    *)
(* binary blob is decoded by.                                             *)
(*                                                                        *)
(* WHAT THE FOURTEEN DO NOT INCLUDE is the point of the file.  No          *)
(* [Admitted], no [Axiom] of this project's beyond the two named           *)
(* reservation [Parameter]s, and -- the thing only [Print Assumptions] can *)
(* certify -- NO [Spec*]/[Link*] MODULE PARAMETER.  ANYTHING ELSE IS A     *)
(* REGRESSION.                                                             *)
(*                                                                        *)
(* WHY THE TARGET IS THE CLOSED COROLLARY and not                          *)
(* [file_adequacy_at_img]: [EchoAssumptions.v]'s reason.  The corollary    *)
(* fixes the functor list at [fileSig] (so every ghost class is realised   *)
(* by [subG] rather than merely assumed -- the anti-vacuity check) and the *)
(* disk at the mkfs image, leaving the three hardware facts and [Hprog].   *)
(*                                                                        *)
(* WHY IT IS OUT OF [iris/_CoqProject], same as its three siblings:        *)
(* [Print Assumptions] re-cooks every opaque proof term in the transitive  *)
(* cone, and paying that on every developer's every build is not worth it. *)
(* Compiled by `make audit-file` / `make audit-file-only` instead.  The    *)
(* commented row in [iris/_CoqProject] is what tells the coverage checker  *)
(* ([tools/proof_coverage.py]) that the file is out of the build ON        *)
(* PURPOSE rather than by accident.                                       *)
(*                                                                        *)
(* KEEP IT TO ONE [Print Assumptions]: consecutive calls share nothing, so *)
(* a second command here would double the bill rather than ride along.     *)
(*                                                                        *)
(* THE OTHER HALF OF THE TRUSTED BASE -- what a reader must READ for the   *)
(* statement to MEAN what they think -- is not an axiom question.  For     *)
(* this theorem it is above all [FileDisc.v]: [disc_f], [good_out_f],      *)
(* [fadm_boot] and [file_phi] ARE the specification, and a [Print          *)
(* Assumptions] of a theorem about the wrong predicate is worth nothing.   *)
(* See tools/tcb/ and claude-notes/design/app-file.md.                     *)
(* ====================================================================== *)
Require Import UInitFile.

Print Assumptions file_adequacy_closed.
