(* ====================================================================== *)
(* PipeAssumptions.v -- THE ASSUMPTION AUDIT of the PIPELINE APPLICATION's *)
(* top-level theorem.                                                     *)
(*                                                                        *)
(* [Print Assumptions] on [UPipeBootAdequacy.pipe_adequacy_pipeSigma]:     *)
(* safety of the whole machine plus the console trace property for the     *)
(* application of claude-notes/design/app-pipe.md -- the user types        *)
(* `echo w1 ... wn' and `echo w1 ... wn | cat' at the console of an        *)
(* unmodified xv6, and nothing but the line and sh's own diagnostics ever  *)
(* reaches the console.                                                    *)
(*                                                                        *)
(* WHY A FIFTH AUDIT FILE, beside [SystemAssumptions.v],                   *)
(* [EchoAssumptions.v], [TreeAssumptions.v] and [FileAssumptions.v]: for   *)
(* [EchoAssumptions.v]'s own reason, and no two of the five cones contain  *)
(* each other.  This one walks [PipeDisc]/[PipeDiscDec]/[PipeOutPure]/     *)
(* [PipeOut]/[PipeLinks]/[AppPipeClaim]/[AppPipe] and none of the other    *)
(* four does.  A grep for [Axiom] and [Admitted] cannot see a sealed       *)
(* [Spec*] module [Parameter]; this is the check that does, for this cone. *)
(*                                                                        *)
(* WHAT THE AUDIT CANNOT SEE, AND IT IS THE POINT OF THIS PARAGRAPH.       *)
(* [pipe_adequacy_pipeSigma] has ONE premise this tree still owes:         *)
(* [Hprog : UPipeBootAdequacy.pipe_prog_law] -- [App.al_programs] at       *)
(* [AppPipe.app_pipe], the first process's exec bundle, which is sh's      *)
(* round at the pipeline line.  A theorem's PREMISES are part of its       *)
(* statement and NEVER appear in a [Print Assumptions] (the echo and file  *)
(* twins make the same point), so the list below says nothing about it:    *)
(* the BINDER LIST of the theorem is the complementary check and neither   *)
(* substitutes for the other.  [Hprog] is a premise and NOT an [Axiom]     *)
(* deliberately -- an axiom would print here and would never be discharged *)
(* by anything, while a premise is discharged the day the round lands, by  *)
(* applying its lemma, with no change to this file.  Until then, read the  *)
(* theorem as: with the first process's exec bundle in hand, the machine   *)
(* is safe and the trace property holds.                                  *)
(*                                                                        *)
(* WHAT IS NOT A PREMISE and would have been: [pipe_both_law] (design      *)
(* section 4.3, the two-writer console arm for the both-execs-failed       *)
(* alternative) does NOT appear here.  It is not a hypothesis of the       *)
(* RECORD -- the record's only open field is [al_programs] -- so it sits   *)
(* inside [Hprog], where the round will name it, and lane PIPE-2W          *)
(* discharges it there.  See the SH-PIPE-ROUND findings block.             *)
(*                                                                        *)
(* EXPECT AT MOST THE ECHO THEOREM'S FOURTEEN, and the same split:         *)
(*                                                                        *)
(*   1  [functional_extensionality_dep]                                    *)
(*   2  [xv6iris_extras.resv_matches] / [_is_valid] -- the LR/SC           *)
(*      reservation predicates, this project's own [Parameter]s            *)
(*  11  Rocq's [PrimString]/[PrimInt63] primitives                         *)
(*                                                                        *)
(* ANYTHING ELSE -- and in particular any [Spec*]/[Link*] module           *)
(* [Parameter] -- IS A REGRESSION.                                         *)
(*                                                                        *)
(* WHY THE TARGET IS THE CLOSED COROLLARY and not [pipe_adequacy_at_img]:  *)
(* [EchoAssumptions.v]'s reason.  The corollary fixes the functor list at  *)
(* [pipeSigma] (so every ghost class is realised by [subG] rather than     *)
(* merely assumed -- the anti-vacuity check) and the disk at the mkfs      *)
(* image, leaving the three hardware facts and [Hprog].                    *)
(*                                                                        *)
(* WHY IT IS OUT OF [iris/_CoqProject], same as its four siblings:         *)
(* [Print Assumptions] re-cooks every opaque proof term in the transitive  *)
(* cone.  Compiled by `make audit-pipe` / `make audit-pipe-only` instead;  *)
(* the commented row in [iris/_CoqProject] is what tells the coverage      *)
(* checker that the file is out of the build ON PURPOSE.                   *)
(*                                                                        *)
(* THE OTHER HALF OF THE TRUSTED BASE -- what a reader must READ for the   *)
(* statement to MEAN what they think -- is not an axiom question.  For     *)
(* this theorem it is above all [PipeDisc.v]: [disc_p], [good_out_p],      *)
(* [palt_ok], [pcont] and [pipe_phi] ARE the specification, and a [Print   *)
(* Assumptions] of a theorem about the wrong predicate is worth nothing.   *)
(* See tools/tcb/ and claude-notes/design/app-pipe.md.                     *)
(* ====================================================================== *)
Require Import UPipeBootAdequacy.

Print Assumptions pipe_adequacy_pipeΣ.
