(* ====================================================================== *)
(* PipeAssumptions.v -- THE ASSUMPTION AUDIT of the PIPELINE APPLICATION's *)
(* top-level theorem.                                                     *)
(*                                                                        *)
(* [Print Assumptions] on [UInitPipeAdequacy.pipe_adequacy_pipeSigma_of_child]:    *)
(* safety of the whole machine plus the console trace property for the     *)
(* application of claude-notes/design/app-pipe.md -- the user types        *)
(* `echo w1 ... wn' and `echo w1 ... wn | cat' at the console of an        *)
(* unmodified xv6, and nothing but the line and sh's own diagnostics ever  *)
(* reaches the console.                                                    *)
(*                                                                        *)
(* WHY A FIFTH AUDIT FILE, beside [SystemAssumptions.v],                   *)
(* [EchoAssumptions.v], [TreeAssumptions.v] and [FileAssumptions.v]: for   *)
(* [EchoAssumptions.v]'s own reason, and no two of the five cones contain  *)
(* each other.  This one walks [PipeDisc]/[PipeDiscDec]/[PipeOutPure]/     *)
(* [PipeOut]/[PipeLinks]/[AppPipeClaim]/[AppPipe] and none of the other    *)
(* four does.  A grep for [Axiom] and [Admitted] cannot see a sealed       *)
(* [Spec*] module [Parameter]; this is the check that does, for this cone. *)
(*                                                                        *)
(* THE TARGET MOVED (lane PIPE-CC), and it is worth saying where to.       *)
(* It used to be [UPipeBootAdequacy.pipe_adequacy_pipeSigma], whose one    *)
(* premise was [Hprog : pipe_prog_law] -- [App.al_programs] at             *)
(* [AppPipe.app_pipe], the WHOLE first process's exec bundle.  That law    *)
(* is discharged now ([UInitPipeAdequacy.pipe_prog_law_of_child]) and what is      *)
(* left is [UInitPipe.sh_pipe_child_law_all]: sh's PIPE-arm child law at   *)
(* the pipeline line, lane SH-PIPE-ROUND-4's.  The corollary audited       *)
(* below carries that one premise instead, and its cone is strictly        *)
(* LARGER than the old target's -- it now walks the whole [Uk*]/[USh*]/    *)
(* [UInit*]/[UEcho*]/[UCat*] program tier as well.                         *)
(*                                                                        *)
(* WHAT THE AUDIT CANNOT SEE, AND IT IS THE POINT OF THIS PARAGRAPH.       *)
(* [pipe_adequacy_pipeSigma_of_child] has ONE premise this tree still      *)
(* owes: [Hchild : UInitPipe.sh_pipe_child_law_all], the pipe child's      *)
(* law.  A theorem's PREMISES are part of its                              *)
(* statement and NEVER appear in a [Print Assumptions] (the echo and file  *)
(* twins make the same point), so the list below says nothing about it:    *)
(* the BINDER LIST of the theorem is the complementary check and neither   *)
(* substitutes for the other.  [Hchild] is a premise and NOT an [Axiom]    *)
(* deliberately -- an axiom would print here and would never be discharged *)
(* by anything, while a premise is discharged the day the round lands, by  *)
(* applying its lemma, with no change to this file.  Until then, read the  *)
(* theorem as: with sh's PIPE-arm child law in hand, the machine is safe   *)
(* and the trace property holds.                                          *)
(*                                                                        *)
(* WHAT IS NOT A PREMISE and would have been: [pipe_both_law] (design      *)
(* section 4.3, the two-writer console arm for the both-execs-failed       *)
(* alternative) does NOT appear here.  It is not a hypothesis of the       *)
(* RECORD -- the record's only open field is [al_programs] -- so it sits   *)
(* inside the child law, where the round names it, and lane PIPE-2W        *)
(* discharges it there.  See the SH-PIPE-ROUND findings block.             *)
(*                                                                        *)
(* EXPECT AT MOST THE ECHO THEOREM'S FOURTEEN -- FOR EACH LIST THIS FILE   *)
(* PRINTS, the anchor's and every frontier one's -- and the same split:    *)
(*                                                                        *)
(*   1  [functional_extensionality_dep]                                    *)
(*   2  [xv6iris_extras.resv_matches] / [_is_valid] -- the LR/SC           *)
(*      reservation predicates, this project's own [Parameter]s            *)
(*  11  Rocq's [PrimString]/[PrimInt63] primitives                         *)
(*                                                                        *)
(* ANYTHING ELSE -- and in particular any [Spec*]/[Link*] module           *)
(* [Parameter] -- IS A REGRESSION.                                         *)
(*                                                                        *)
(* WHY THE TARGET IS THE CLOSED COROLLARY and not [pipe_adequacy_at_img]:  *)
(* [EchoAssumptions.v]'s reason.  The corollary fixes the functor list at  *)
(* [pipeSigma] (so every ghost class is realised by [subG] rather than     *)
(* merely assumed -- the anti-vacuity check) and the disk at the mkfs      *)
(* image, leaving the three hardware facts and [Hprog].                    *)
(*                                                                        *)
(* WHY IT IS OUT OF [iris/_CoqProject], same as its four siblings:         *)
(* [Print Assumptions] re-cooks every opaque proof term in the transitive  *)
(* cone.  Compiled by `make audit-pipe` / `make audit-pipe-only` instead;  *)
(* the commented row in [iris/_CoqProject] is what tells the coverage      *)
(* checker that the file is out of the build ON PURPOSE.                   *)
(*                                                                        *)
(* THE OTHER HALF OF THE TRUSTED BASE -- what a reader must READ for the   *)
(* statement to MEAN what they think -- is not an axiom question.  For     *)
(* this theorem it is above all [PipeDisc.v]: [disc_p], [good_out_p],      *)
(* [palt_ok], [pcont] and [pipe_phi] ARE the specification, and a [Print   *)
(* Assumptions] of a theorem about the wrong predicate is worth nothing.   *)
(* See tools/tcb/ and claude-notes/design/app-pipe.md.                     *)
(*                                                                        *)
(* THE FRONTIER GOES IN THIS FILE TOO, and it is the second half of what   *)
(* the target above cannot see.  [Hchild] is a premise, so the print       *)
(* below it says nothing about the lemmas a round lands ON THE WAY to      *)
(* discharging it: those sit outside the corollary's cone until the day    *)
(* the law is applied.  Auditing them is a real need and it is THIS        *)
(* file's job -- ONE audit file per application, as for the other four.    *)
(* A lane does NOT add a [<Lane>Assumptions.v] of its own; it edits the    *)
(* FRONTIER block below, and drops a line from it once the lemma enters    *)
(* the corollary's cone (at which point the print above covers it).        *)
(*                                                                        *)
(* AUDIT THE TOP OF THE FRONTIER, NOT EACH LEMMA UNDER IT.  [Print         *)
(* Assumptions] walks a whole cone, so printing the round law subsumes     *)
(* printing the hundred lemmas its proof uses; a list of those is a lane   *)
(* journal, not a check.  Keep this block to the few statements the open   *)
(* premise is actually being built out of.                                 *)
(* ====================================================================== *)
Require Import UInitPipeAdequacy.

(* ---- THE TARGET, AND IT HAS NO PREMISE (lane SH-PIPE-ROUND-14) ----
   [pipe_adequacy_pipeΣ_final] is [pipe_adequacy_pipeΣ_of_child] with
   [Hchild] DISCHARGED ([UInitPipe.sh_pipe_child_law_all_holds]) and the
   functor list extended by [PipeProto.pipeProtoΣ], which
   [UPipeBootAdequacy.pipeΣ] does not contain (see that theorem's own
   header, and the lane's Findings).  Its binder list is now three
   HARDWARE facts about the initial machine state and nothing else, so
   the complementary "read the binders too" check has nothing left in it
   and the list below is the whole trusted base. *)
Goal True. idtac "---- UInitPipeAdequacy.pipe_adequacy_pipeΣ_final". Abort.
Print Assumptions pipe_adequacy_pipeΣ_final.

(* ...and the premise-carrying corollary it supersedes, kept because its
   [pipeΣ] is the anchor's own functor list. *)
Goal True. idtac "---- UInitPipeAdequacy.pipe_adequacy_pipeΣ_of_child". Abort.
Print Assumptions pipe_adequacy_pipeΣ_of_child.

(* ---- THE FRONTIER: EMPTY.  Every statement that used to stand here --
   [UShPipeRound.sh_round_holds_pipe], [UShPipeCatSlot.pipe_sh_cat_slot],
   [UInitPipe.pipe_Hinit_boot] -- is inside the target's cone now, so the
   print above covers it (the file's own rule: drop a line from the
   frontier once the lemma enters the corollary's cone). ---- *)
