(* ====================================================================== *)
(* TreeAssumptions.v -- THE ASSUMPTION AUDIT of the TREE APPLICATION's     *)
(* era-0 obligation.                                                      *)
(*                                                                        *)
(* [Print Assumptions] on [TreeImg.tree_Happ_init]:                        *)
(* [App.xv6_app_adequacy]'s [Happ_init] at [AppTree.app_tree], with the    *)
(* disk at the image mkfs wrote: when the machine is switched on with     *)
(* that disk, the live file system is a well-formed, ROOTED tree and its   *)
(* root is a directory, so the tree application's claim can be born.       *)
(*                                                                        *)
(* WHY THE TARGET IS NOT A WHOLE-SYSTEM THEOREM, and when it will be.      *)
(* [App.xv6_app_adequacy] at [AppTree.app_tree] is not yet provable: its   *)
(* [Hinit_boot] -- the first process's exec bundle -- is open, and the     *)
(* three walls that keep it open are recorded in                           *)
(* claude-notes/design/user-tree.md section 8.  This audit is the part of  *)
(* that theorem's cone that EXISTS: the era-0 claim at the literal image,  *)
(* together with everything [AppTree.v] / [TreeView.v] / [TreeMove.v] and  *)
(* the image checks it walks.  When [Hinit_boot] lands, this file's        *)
(* [Print Assumptions] moves to the closed corollary and nothing else      *)
(* about the target changes.                                              *)
(*                                                                        *)
(* WHY IT IS A THIRD AUDIT FILE, beside [SystemAssumptions.v] and          *)
(* [EchoAssumptions.v]: for [EchoAssumptions.v]'s own reason.  Neither     *)
(* cone contains this one -- the system theorem walks no application tier  *)
(* at all, and the echo theorem walks [AppEcho]/[EchoOut]/[USh*] and       *)
(* never [AppTree]/[TreeView]/[TreeMove]/[TreeImg].  A grep for [Axiom]    *)
(* and [Admitted] cannot see a sealed [Spec*] module [Parameter]; this is  *)
(* the check that does.                                                   *)
(*                                                                        *)
(* WHY IT IS OUT OF [iris/_CoqProject], same as its two siblings:          *)
(* [Print Assumptions] re-cooks every opaque proof term in the transitive  *)
(* cone, and paying that on every developer's every build is not worth it. *)
(* Compiled by `make audit-tree` / `make audit-tree-only` instead.         *)
(*                                                                        *)
(* KEEP IT TO ONE [Print Assumptions]: consecutive calls share nothing, so *)
(* a second command here would double the bill rather than ride along.     *)
(*                                                                        *)
(* THE OTHER HALF OF THE TRUSTED BASE -- what a reader must READ for the   *)
(* statement to MEAN what they think -- is not an axiom question.  For     *)
(* this obligation it is above all [TreeView.aview_tree_wf] /              *)
(* [TreeView.aview_rooted] and [AppTree.tree_pred]: the claim IS the       *)
(* specification.  See tools/tcb/ and claude-notes/design/user-tree.md.    *)
(* ====================================================================== *)
Require Import TreeImg.

Print Assumptions tree_Happ_init.
